// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdI4bjMAF-xC6AQVDbgps6L-CLG9NKwv4',
    appId: '1:594037245834:web:7d2d5fd798a040dd622a73',
    messagingSenderId: '594037245834',
    projectId: 'true-hadith-59fb0',
    authDomain: 'true-hadith-59fb0.firebaseapp.com',
    storageBucket: 'true-hadith-59fb0.firebasestorage.app',
    measurementId: 'G-L6X7DZY0M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEolQjr70nobYNigQG1EdI5Tbtv2GsEAk',
    appId: '1:594037245834:android:7dd62e05d3f3bf83622a73',
    messagingSenderId: '594037245834',
    projectId: 'true-hadith-59fb0',
    storageBucket: 'true-hadith-59fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Fvryg9Dlh9vxjslqiCTJ6Pk5eb75kAE',
    appId: '1:594037245834:ios:ddb4dd91f9c58ebf622a73',
    messagingSenderId: '594037245834',
    projectId: 'true-hadith-59fb0',
    storageBucket: 'true-hadith-59fb0.firebasestorage.app',
    iosBundleId: 'com.example.trueHadith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Fvryg9Dlh9vxjslqiCTJ6Pk5eb75kAE',
    appId: '1:594037245834:ios:ddb4dd91f9c58ebf622a73',
    messagingSenderId: '594037245834',
    projectId: 'true-hadith-59fb0',
    storageBucket: 'true-hadith-59fb0.firebasestorage.app',
    iosBundleId: 'com.example.trueHadith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdI4bjMAF-xC6AQVDbgps6L-CLG9NKwv4',
    appId: '1:594037245834:web:53a1ed85d8c03dcb622a73',
    messagingSenderId: '594037245834',
    projectId: 'true-hadith-59fb0',
    authDomain: 'true-hadith-59fb0.firebaseapp.com',
    storageBucket: 'true-hadith-59fb0.firebasestorage.app',
    measurementId: 'G-3CKL37XQB0',
  );
}
